name: example
description: An example for riverbloc with Flutter.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  hooks_riverpod: ^3.0.0
  riverbloc:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
