name: bloc_counters
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  flutter:
    sdk: flutter
  #flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  flutter_hooks_bloc: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
