name: flutter_hooks_bloc
description: >-
  A flutter_bloc reimplementation based on flutter_hooks
  with the same API.
version: 0.17.0
homepage: https://github.com/kranfix/riverbloc

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  #flutter_coverage_badge: ^0.0.1+1

flutter:
